name: AmpleChatBot
main: com.drevelopment.amplechatbot.bukkit.BukkitPlugin
version: ${version}
author: Drepic26, matthewl6970, licks92
softdepend: [Vault]

commands:
 answer:
  description: Sets the response to Question ID.
  usage: /<command> <QID> <answer>
 question:
  description: Adds question or key phrase.
  usage: /<command> <question or key phrase>
 qlist:
  description: lists question or key phrase.
  usage: /<command> [QID][question][keyphrase]
 delquestion:
  description: deletes questions or key phrases.
  usage: /<command> <QID>
 amplesay:
  description:  Allows to use say command.
  usage: /<command> <messageD>
 ample:
  description: Displays help for this plugin.
  usage: /<command> <subcommand>
 ampletoggle:
  description: Toggle active state of the bot
  usage: /<command>

permissions:
 ample.*:
  description: Gives access to all Ample commands
  default: op
  children:
   ample.invoke: true
   ample.edit: true
   ample.qlist: true
   ample.delete: true
   ample.say: true
   ample.allowabuse: true
   ample.toggle: true
 ample.invoke:
  description: Allows people to invoke responses.
  default: true
 ample.edit:
  description: Allows to editing/updating/adding of questions and answers.
  default: op
 ample.qlist:
  description: Allows to view the list of questions.
  default: op
 ample.delete:
  description: Allows to delete questions.
  default: op
 ample.say:
  description: Allows to use say command.
  default: op
 ample.allowabuse:
  description: Allows to bypass abuse routines.
  default: op
 ample.toggle:
  description: Allows to toggle active state of the bot.
  default: op
